# default
service      {
    listen 127.0.0.1:8080;
    listen 127.0.0.2:8080;
    #listen 127.0.0.3:8080;
    server_name main_server;
    max_body_size 1000000;        # service-wide
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # root
    location / {
	    error_page 404 /errors/404.html;
	    root ./root/;
	    methods GET POST DELETE;
	    default_file index.html;
	    #@TODO: mudar listing para directory_listing
	    listing on;
	    #return 301 https://example.com$request_uri;
    }

    # upload
    location /upload {
        methods POST;
        upload on;
        upload_dir upload_dir/;
    }

    # CGI
    location /scripts {
        root ./root/cgi-bin/;
        methods GET POST;
        cgi .py /usr/bin/python3;
    }
}

#service {
#    listen 127.0.0.4:8081;
#    server_name secondary_server;
#    max_body_size 1000000;        # service-wide
#    error_page 400 tests/errors/400.html;
#    error_page 404 tests/errors/404.html;
#    error_page 500 tests/errors/500.html;
#
#    location / 
#    {
#	    methods GET POST DELETE;
#    }
#
#    # root
#    location /static_files {
#	    error_page 404 www/errors/404.html;
#	    error_page 301 www/errors/301.html;
#	    root www/;
#	    methods GET POST DELETE;
#	    #default_file index.html;
#	    listing on;
#	    #return 301 https://example.com$request_uri;
#    }
#
#    # upload
#    location /upload {
#        root root/uploads/;
#        methods POST;
#        upload on;
#        upload_dir upload_dir/;
#    }
#
#    # CGI
#    location /scripts {
#        root root/cgi-bin/;
#        methods GET POST;
#        cgi .py /usr/bin/python3;
#    }
#}
