# default
service {
    listen 127.0.0.1:8080;
    server_name main_server;
    max_body_size 1000000;        # service-wide
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # root
    location / {
	    error_page 404 /errors/404.html;
	    root root/;
	    methods GET POST DELETE;
	    default_file index.html;
	    listing on;
	    return 301 https://example.com$request_uri;
    }

    # upload
    location /upload {
        root root/uploads/;
        methods POST;
        upload on;
        upload_dir upload_dir/;
    }

    # CGI
    location /scripts {
        root root/cgi-bin/;
        methods GET POST;
        cgi .py path_to_py.py;
    }
}

service {
    listen 127.0.0.2:8081;
    server_name secondary_server;
    max_body_size 1000000;        # service-wide
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # root
    location / {
	    error_page 404 /errors/404.html;
	    root root/;
	    methods GET POST DELETE;
	    default_file index.html;
	    listing on;
	    return 301 https://example.com$request_uri;
    }

    # upload
    location /upload {
        root root/uploads/;
        methods POST;
        upload on;
        upload_dir upload_dir/;
    }

    # CGI
    location /scripts {
        root root/cgi-bin/;
        methods GET POST;
        cgi .py path_to_py.py;
    }
}
